config/routes.rb
Rails.application.routes.draw do

  get '/signup', to: "users#new"
  root 'static_pages#home'
  get '/help', to: "static_pages#help"
  get '/about', to: "static_pages#about"
  get '/contact', to: "static_pages#contact"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'


  get '/edit/:id', to: "users#edit"
  post '/edit/:id', to: "users#update" 


  resources :users

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  before_save {self.email = email.downcase}
  validates :first_name, presence: true, length:{maximum: 19}
  validates :email, presence: true, length: {maximum: 254}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i

  validates :email, format: { with: VALID_EMAIL_REGEX}
  validates :email, uniqueness: true
  validates :password, presence: true, length: { minimum: 6}, allow_nil: true
  validates :password_confirmation, presence: true, length: { minimum: 6}


  def name
    [first_name, last_name].join(' ')
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user&.authenticate(params[:session][:password])
      log_in user
      redirect_back_or user
    else
      flash.now[:danger] = "failed"
      render 'new' 
    end
  end

  def destroy
    log_out
    redirect_to root_path
  end


end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :index]
  before_action :correct_user, only: [:edit, :update]

  def index
    @users = User.paginate(page: params[:page], per_page: 20)

  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    if @user.save
      log_in @user
      flash[:success] = "succeeded creating new user!"
      redirect_to @user
    else
      flash.now[:notice] = "failed to crate a new user!"
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])

  end

  def edit 
    @user = User.find(params[:id])

  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = 'update success'
      redirect_to user_path
    else
      flash[:danger] = 'failed to update'
      render 'edit'

    end

  end


  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_path
  end
  



  private
  def user_params
    params.require(:user).permit(:first_name, :email, :password, :password_confirmation)
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to(root_url) unless current_user?(@user)
  end





end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by(id: session[:user_id])
    end
  end

  def current_user?(user)
    user && user == current_user
  end
 


  #ユーザーがログインしていればtrue, その他ならfalseを返す
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil 
  end


  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end




end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/test_helper.rb
module TestHelper
  def is_logged_in?
    !session[:user_id].nil?
  end

  def log_in_as(user)
    session[:user_id] = user.id 
  end  


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
    by <a href="https://www.kktak02.com"> Takuya Kinoshita</a>
  </small>

  <nav>
    <ul>
      <li><%= link_to "About", about_path %> </li>
      <li><%= link_to "Contact", contact_path %> </li>
      <li><a href="https://news.railstutorial.org">News</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_form.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @user, local: true) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

  </div>
</div>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "sample app", "#", id: "logo" %>
        <nav>
          <ul class="nav navbar-nav navbar-right">
		<li><%= link_to "Home", root_path %></li>
		<li><%= link_to "Help", help_path %></li>
		<% if logged_in? %>	
			<li><%= link_to "Users", users_path  %></li>
			<li><%= link_to "Profile", current_user %></li>
			<li><%= link_to "Settings", "#" %></li>
			<li><%= link_to "Edit", edit_user_path(current_user) %></li>
			<li><%= link_to "Log out", logout_path, method: :delete %></li>
		<% else %>
			<li><%= link_to "Log in", login_path %></li>

		<% end %>
	</ul>
	</nav>
	</div>
	</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= favicon_link_tag 'favicon.ico' %>
    <title><%= yield(:title) %> | Ruby on Rails TUtorial Sample App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
     <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%=message_type %>"><%= message %></div>
    <% end %>


    <%= yield %>
     <div class="debug" >
     <%= debug(params) if Rails.env.development? %>
     </div>

  </div>
     <%= render 'layouts/footer' %>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation" >
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, "About Me") %>

<h1></h1>

app/views/static_pages/contact.html.erb
<h1>Contact</h1>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %> | Ruby on Rails Tutorial Sample App</title>
  </head>

<body>


<div class="center jumbotron">
  <h1>Welcome to the Sample App</h1>

<h2>
  This is the home page for the
  <a href="https://railstutorial.jp/">Ruby on Rails Tutorial</a>
  sample application.
</h2>
  <%= link_to "Sign up now!", signup_path, class:"btn btn-primary" %>


</div>

<%= link_to image_tag("rails.svg", alt: "Rails logo", width: "200px"), "https://rubyonrails.org/" %>


</body>
</html>

app/views/users/edit.html.erb
<%= render '/layouts/form' %>

app/views/users/index.html.erb
<% provide(:title, "All users") %>


<%= will_paginate %>

<h1>All users</h1>
<h2>
<% @users.each do |user| %>
<li><%= user.name %>
<% if current_user.admin? && !current_user?(user) %>
| <%= link_to "delete", user, method: :delete, data: { confirm: "You sure?"} %>
<% end %>
</li>
<% end %>

</h2>

app/views/users/new.html.erb
<h1>Users#new</h1>

<%= render 'shared/error_messages' %>

<%= form_for @user do |f| %>

 <div class="form-group">
  <%= f.label :first_name %>
  <%= f.text_field :first_name, class:"form-control" %>
 </div>

 <div class="form-group">
  <%= f.label :last_name %>
  <%= f.text_field :last_name, class:"form-control" %>
 </div>

 <div class="form-group" >
  <%= f.label :email  %>
  <%= f.text_field :email, class:"form-control" %>
 </div>



 <div class="form-group" >
  <%= f.label :password %>
  <%= f.password_field :password, class:"form-control" %>
 </div>

 <div class="form-group">
  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation, class:"form-control" %>
 </div>


 <%= f.submit "Create new user", class:"btn btn-primary" %>

<% end %>

app/views/users/show.html.erb
<h1> <%= @user.name %> </h1>